# Library discovery helpers (included from root CMakeLists.txt)

find_package(PkgConfig QUIET)

function (resolve_version OutVar Value)
    if ("${Value}" STREQUAL "")
        set(${OutVar} "no version" PARENT_SCOPE)
    else ()
        set(${OutVar} "${Value}" PARENT_SCOPE)
    endif ()
endfunction()

function (check_required Prefix PackageName Mode)
    if (Mode STREQUAL "REQUIRED")
        message(FATAL_ERROR "Failed to locate REQUIRED package: " ${Prefix})
    else ()
        resolve_version(package_version "${${PackageName}_VERSION}")
        message("    " ${Prefix} ": " ${package_version} " [not found]")
    endif ()
endfunction()

function (apply_cmake_target Target Interface Prefix PackageName ImportedTarget)
    if (DEFINED ${Prefix}_MODULE_VERSION AND NOT "${${Prefix}_MODULE_VERSION}" STREQUAL "")
        set(_version_value "${${Prefix}_MODULE_VERSION}")
    else ()
        set(_version_value "${${PackageName}_VERSION}")
    endif ()
    resolve_version(package_version "${_version_value}")
    message("    " ${Prefix} ": " ${package_version} " [cmake]")

    target_compile_definitions(${Target} PRIVATE "MANGO_ENABLE_${Prefix}")
    target_link_libraries(${Target} ${Interface} ${ImportedTarget})
endfunction()

function (apply_pkgconfig_target Target Interface Prefix)
    if (DEFINED ${Prefix}_MODULE_VERSION AND NOT "${${Prefix}_MODULE_VERSION}" STREQUAL "")
        set(_version_value "${${Prefix}_MODULE_VERSION}")
    else ()
        set(_version_value "${${Prefix}_VERSION}")
    endif ()
    resolve_version(package_version "${_version_value}")
    message("    " ${Prefix} ": " ${package_version} " [pkgconfig]")

    target_compile_definitions(${Target} PRIVATE "MANGO_ENABLE_${Prefix}")
    target_include_directories(${Target} ${Interface} ${${Prefix}_INCLUDE_DIRS})
    target_link_directories(${Target} ${Interface} ${${Prefix}_LIBRARY_DIRS})
    target_link_libraries(${Target} ${Interface} ${${Prefix}_LIBRARIES})
endfunction()

function (apply_manual_target Target Interface Prefix)
    if (DEFINED ${Prefix}_MODULE_VERSION AND NOT "${${Prefix}_MODULE_VERSION}" STREQUAL "")
        set(_version_value "${${Prefix}_MODULE_VERSION}")
    else ()
        set(_version_value "")
    endif ()
    resolve_version(package_version "${_version_value}")
    message("    " ${Prefix} ": " ${package_version} " [manual]")

    target_compile_definitions(${Target} PRIVATE "MANGO_ENABLE_${Prefix}")
    target_include_directories(${Target} ${Interface} ${${Prefix}_INCLUDE_DIRS})
    target_link_directories(${Target} ${Interface} ${${Prefix}_LIBRARY_DIRS})
    target_link_libraries(${Target} ${Interface} ${${Prefix}_LIBRARIES})
endfunction()

function (check_manual_override Prefix Result)
    if (DEFINED ${Prefix}_LIBRARIES AND DEFINED ${Prefix}_INCLUDE_DIRS)
        set(${Result} TRUE PARENT_SCOPE)
    else ()
        set(${Result} FALSE PARENT_SCOPE)
    endif ()
endfunction()

function (mango_resolve_located_version Prefix PackageName ModuleName Method out_var)
    set(_version "")

    if (Method STREQUAL "pkgconfig")
        if (DEFINED ${Prefix}_VERSION AND NOT "${${Prefix}_VERSION}" STREQUAL "")
            set(_version "${${Prefix}_VERSION}")
        endif ()
    else ()
        foreach (_name IN ITEMS ${PackageName} ${Prefix})
            if (NOT _version STREQUAL "")
                break ()
            endif ()
            foreach (_suffix IN ITEMS VERSION VERSION_STRING)
                set(_var ${_name}_${_suffix})
                if (DEFINED ${_var} AND NOT "${${_var}}" STREQUAL "")
                    set(_version "${${_var}}")
                    break ()
                endif ()
            endforeach ()
        endforeach ()
    endif ()

    if (_version STREQUAL "" AND PkgConfig_FOUND AND NOT ModuleName STREQUAL "")
        pkg_check_modules(${Prefix}_PKGVER QUIET ${ModuleName})
        if (${Prefix}_PKGVER_FOUND AND DEFINED ${Prefix}_PKGVER_VERSION)
            set(_version "${${Prefix}_PKGVER_VERSION}")
        endif ()
    endif ()

    set(${out_var} ${_version} PARENT_SCOPE)
endfunction()

function (locate_module Prefix ModuleName PackageName ImportedTarget Version OutFound)
    set(_found FALSE)
    set(_imported_target ${ImportedTarget})

    if (NOT PackageName STREQUAL "")
        if (Version STREQUAL "0")
            find_package(${PackageName} QUIET)
        else ()
            find_package(${PackageName} ${Version} QUIET)
        endif ()

        if (${PackageName}_FOUND)

            if (${Prefix} STREQUAL "LZ4")
                # Debian 13 on Raspberry Pi 5 uses 'LZ4::lz4'
                if (TARGET LZ4::lz4 AND NOT TARGET lz4::lz4)
                    add_library(lz4::lz4 ALIAS LZ4::lz4)
                endif ()
            endif ()

            if (${Prefix} STREQUAL "ZSTD")
                if (TARGET zstd::libzstd)
                    # brew / vcpkg imported target is 'zstd::libzstd'
                else ()
                    # apt / pacman don't correctly export target but this works
                    set(_imported_target "zstd")
                endif ()
            endif ()

            if (NOT _imported_target STREQUAL "")
                set(_found TRUE)
                set(_method "cmake")
                set(_package_name ${PackageName})
            elseif (DEFINED ${Prefix}_INCLUDE_DIRS AND DEFINED ${Prefix}_LIBRARIES)
                set(_found TRUE)
                set(_method "manual")
            endif ()
        endif ()
    endif ()

    if (NOT _found AND PkgConfig_FOUND AND NOT ModuleName STREQUAL "")
        if (Version STREQUAL "0")
            pkg_check_modules(${Prefix} QUIET ${ModuleName})
        else ()
            pkg_check_modules(${Prefix} QUIET ${ModuleName}>=${Version})
        endif ()

        if (${Prefix}_FOUND)
            set(_found TRUE)
            set(_method "pkgconfig")
        endif ()
    endif ()

    if (NOT _found)
        check_manual_override(${Prefix} MANUAL_OVERRIDE_FOUND)
        if (MANUAL_OVERRIDE_FOUND)
            set(_found TRUE)
            set(_method "manual")
        endif ()
    endif ()

    # Arch Linux jxrlib ships headers and libs but no pkg-config or cmake config
    if (NOT _found AND ${Prefix} STREQUAL "JXR")
        find_path(JXR_INCLUDE_DIRS NAMES JXRGlue.h PATH_SUFFIXES jxrlib)
        find_library(JXR_JPEGXR_LIBRARY NAMES jpegxr)
        find_library(JXR_JXRGLUE_LIBRARY NAMES jxrglue)

        if (JXR_INCLUDE_DIRS AND JXR_JPEGXR_LIBRARY AND JXR_JXRGLUE_LIBRARY)
            set(JXR_LIBRARIES ${JXR_JXRGLUE_LIBRARY} ${JXR_JPEGXR_LIBRARY})
            set(_found TRUE)
            set(_method "manual")
        endif ()
    endif ()

    set(${OutFound} ${_found} PARENT_SCOPE)
    set(${Prefix}_FOUND ${_found} PARENT_SCOPE)
    if (_found)
        mango_resolve_located_version(${Prefix} "${PackageName}" "${ModuleName}" ${_method} _module_version)
        set(${Prefix}_MODULE_VERSION ${_module_version} PARENT_SCOPE)
        set(${Prefix}_LOCATE_METHOD ${_method} PARENT_SCOPE)
        if (DEFINED _package_name)
            set(${Prefix}_PACKAGE_NAME ${_package_name} PARENT_SCOPE)
        endif ()
        if (DEFINED _imported_target)
            set(${Prefix}_IMPORTED_TARGET ${_imported_target} PARENT_SCOPE)
        endif ()
        if (_method STREQUAL "manual" OR _method STREQUAL "pkgconfig")
            foreach (_suffix IN ITEMS INCLUDE_DIRS LIBRARY_DIRS LIBRARIES)
                if (DEFINED ${Prefix}_${_suffix})
                    set(${Prefix}_${_suffix} ${${Prefix}_${_suffix}} PARENT_SCOPE)
                endif ()
            endforeach ()
        endif ()
    endif ()
endfunction()

function (find_module Target Prefix Interface Mode ModuleName PackageName ImportedTarget Version)
    locate_module("${Prefix}" "${ModuleName}" "${PackageName}" "${ImportedTarget}" "${Version}" _found)

    if (_found)
        if (${Prefix}_LOCATE_METHOD STREQUAL "cmake")
            apply_cmake_target(${Target} ${Interface} ${Prefix} "${${Prefix}_PACKAGE_NAME}" "${${Prefix}_IMPORTED_TARGET}")
        elseif (${Prefix}_LOCATE_METHOD STREQUAL "pkgconfig")
            apply_pkgconfig_target(${Target} ${Interface} ${Prefix})
        elseif (${Prefix}_LOCATE_METHOD STREQUAL "manual")
            apply_manual_target(${Target} ${Interface} ${Prefix})
        endif ()
        return ()
    endif ()

    if (NOT PackageName STREQUAL "")
        check_required(${Prefix} ${PackageName} ${Mode})
    endif ()
endfunction()

function (find_libdeflate Target Interface Mode)
    if (BUILD_SHARED_LIBS)
        # For shared builds, prefer shared libraries
        set(TARGET_NAMES
            "libdeflate::libdeflate_shared"    # Standard CMake target (Linux/macOS)
            "libdeflate"                       # VCPKG target name (usually shared)
            "libdeflate::libdeflate"           # Alternative VCPKG target
            "libdeflate::libdeflate_static"    # Fallback to static if shared not available
        )
    else ()
        # For static builds, prefer static libraries
        set(TARGET_NAMES
            "libdeflate::libdeflate_static"    # Standard CMake target (Linux/macOS)
            "libdeflate"                       # VCPKG target name (usually static)
            "libdeflate::libdeflate"           # Alternative VCPKG target
            "libdeflate::libdeflate_shared"    # Fallback to shared if static not available
        )
    endif ()

    find_package(libdeflate QUIET)
    if (libdeflate_FOUND)
        foreach(ImportedTarget ${TARGET_NAMES})
            if (TARGET ${ImportedTarget})
                apply_cmake_target(${Target} ${Interface} "LIBDEFLATE" "libdeflate" ${ImportedTarget})
                return()
            endif ()
        endforeach ()
    endif ()

    if (PkgConfig_FOUND)
        pkg_check_modules(LIBDEFLATE QUIET libdeflate)
        if (LIBDEFLATE_FOUND)
            apply_pkgconfig_target(${Target} ${Interface} LIBDEFLATE)
            return()
        endif ()
    endif ()

    check_manual_override("LIBDEFLATE" MANUAL_OVERRIDE_FOUND)
    if (MANUAL_OVERRIDE_FOUND)
        apply_manual_target(${Target} ${Interface} "LIBDEFLATE")
        return()
    endif ()

    check_required("LIBDEFLATE" "libdeflate" ${Mode})
endfunction()

function (mango_probe_image_format_dependencies)
    if (IMAGE_FORMAT_JXR)
        locate_module(JXR libjxr JXR "" 0 _found)
        if (NOT _found)
            message("    JXR: disabling IMAGE_FORMAT_JXR")
            set(IMAGE_FORMAT_JXR OFF PARENT_SCOPE)
        endif ()
    endif ()

    if (IMAGE_FORMAT_JXL)
        locate_module(JXL libjxl "" "" 0.7 _jxl_found)
        locate_module(JXL_THREADS libjxl_threads "" "" 0.7 _jxl_threads_found)
        if (NOT _jxl_found OR NOT _jxl_threads_found)
            message("    JXL: disabling IMAGE_FORMAT_JXL")
            set(IMAGE_FORMAT_JXL OFF PARENT_SCOPE)
        endif ()
    endif ()

    if (IMAGE_FORMAT_JP2)
        locate_module(JP2 libopenjp2 OpenJPEG openjp2 2.4.0 _found)
        if (NOT _found)
            message("    JP2: disabling IMAGE_FORMAT_JP2")
            set(IMAGE_FORMAT_JP2 OFF PARENT_SCOPE)
        endif ()
    endif ()

    if (IMAGE_FORMAT_WEBP)
        locate_module(WEBP libwebp WebP WebP::webp 1.3.2 _found)
        if (NOT _found)
            message("    WEBP: disabling IMAGE_FORMAT_WEBP")
            set(IMAGE_FORMAT_WEBP OFF PARENT_SCOPE)
        endif ()
    endif ()

    if (IMAGE_FORMAT_WP2)
        locate_module(WP2 wp2 wp2 webp2 0 _found)
        if (NOT _found)
            message("    WP2: disabling IMAGE_FORMAT_WP2")
            set(IMAGE_FORMAT_WP2 OFF PARENT_SCOPE)
        endif ()
    endif ()

    if (IMAGE_FORMAT_AVIF)
        locate_module(AVIF libavif libavif avif 1.0.0 _found)
        if (NOT _found)
            message("    AVIF: disabling IMAGE_FORMAT_AVIF")
            set(IMAGE_FORMAT_AVIF OFF PARENT_SCOPE)
        endif ()
    endif ()

    if (IMAGE_FORMAT_HEIF)
        locate_module(HEIF libheif libheif heif 1.13.0 _found)
        if (NOT _found)
            message("    HEIF: disabling IMAGE_FORMAT_HEIF")
            set(IMAGE_FORMAT_HEIF OFF PARENT_SCOPE)
        endif ()
    endif ()

    if (IMAGE_FORMAT_CAMERA)
        set(_libraw_found FALSE)
        if (PkgConfig_FOUND)
            pkg_check_modules(LIBRAW QUIET libraw>=0.20.0)
            if (LIBRAW_FOUND)
                set(_libraw_found TRUE)
            endif ()
        endif ()
        if (NOT _libraw_found)
            message("    LIBRAW: disabling IMAGE_FORMAT_CAMERA")
            set(IMAGE_FORMAT_CAMERA OFF PARENT_SCOPE)
        endif ()
    endif ()
endfunction()

function (mango_link_libraries)
    message("[Required Libraries: core]")

    find_module(mango-core ZLIB ${INTERFACE} REQUIRED zlib ZLIB ZLIB::ZLIB 0)
    find_module(mango-core ZSTD ${INTERFACE} REQUIRED libzstd zstd zstd::libzstd 0)
    find_module(mango-core FMT PUBLIC REQUIRED "" fmt fmt::fmt 8.0)
    find_libdeflate(mango-core ${INTERFACE} REQUIRED)

    message("[Required Libraries: image]")

    find_module(mango-image ZLIB ${INTERFACE} REQUIRED zlib ZLIB ZLIB::ZLIB 0)
    find_module(mango-image ZSTD ${INTERFACE} REQUIRED libzstd zstd zstd::libzstd 0)
    find_module(mango-image LCMS2 PRIVATE REQUIRED lcms2 lcms2 lcms2::lcms2 0)

    if (BUILD_IMPORT3D)
        message("[Required Libraries: import3d]")
        find_module(mango-import3d SIMDJSON ${INTERFACE} REQUIRED simdjson simdjson simdjson::simdjson 0)
    endif ()

    message("[Optional Libraries: core]")

    if (LIBRARY_BZIP2)
        find_module(mango-core BZIP2 ${INTERFACE} OPTIONAL "" BZip2 BZip2::BZip2 0)
    endif ()

    if (LIBRARY_LZ4)
        find_module(mango-core LZ4 ${INTERFACE} OPTIONAL liblz4 lz4 lz4::lz4 0)
    endif ()

    if (LIBRARY_ISAL)
        find_module(mango-core ISAL ${INTERFACE} OPTIONAL libisal unofficial-isal unofficial::isal::isal 0)
    endif ()

    message("[Optional Libraries: image]")

    if (LIBRARY_ISAL)
        find_module(mango-image ISAL ${INTERFACE} OPTIONAL libisal unofficial-isal unofficial::isal::isal 0)
    endif ()

    if (IMAGE_FORMAT_JXR)
        find_module(mango-image JXR ${INTERFACE} OPTIONAL libjxr JXR "" 0)
    endif ()

    if (IMAGE_FORMAT_JXL)
        find_module(mango-image JXL ${INTERFACE} OPTIONAL libjxl "" "" 0.7)
        find_module(mango-image JXL_THREADS ${INTERFACE} OPTIONAL libjxl_threads "" "" 0.7)
    endif ()

    if (IMAGE_FORMAT_JP2)
        find_module(mango-image JP2 ${INTERFACE} OPTIONAL libopenjp2 OpenJPEG openjp2 2.4.0)
    endif ()

    if (IMAGE_FORMAT_WEBP)
        find_module(mango-image WEBP ${INTERFACE} OPTIONAL libwebp WebP WebP::webp 1.3.2)
        if (TARGET WebP::webpdemux)
            target_link_libraries(mango-image ${INTERFACE} WebP::webpdemux)
        endif ()
    endif ()

    if (IMAGE_FORMAT_WP2)
        find_module(mango-image WP2 ${INTERFACE} OPTIONAL wp2 wp2 webp2 0)
    endif ()

    if (IMAGE_FORMAT_AVIF)
        find_module(mango-image AVIF ${INTERFACE} OPTIONAL libavif libavif avif 1.0.0)
    endif ()

    if (IMAGE_FORMAT_HEIF)
        find_module(mango-image HEIF ${INTERFACE} OPTIONAL libheif libheif heif 1.13.0)
    endif ()

    if (IMAGE_FORMAT_CAMERA)
        # LibRaw ships only a pkg-config file (no CMake package config). Its .pc pulls in
        # bare link tokens (-lstdc++, OpenMP, lcms2 via Requires); adding those as plain
        # library names defeats CMake's link de-duplication and ends up duplicating every
        # other pkg-config library on the link line. Linking through an imported target
        # keeps those flags encapsulated and the link line clean.
        if (PkgConfig_FOUND)
            pkg_check_modules(LIBRAW QUIET IMPORTED_TARGET libraw>=0.20.0)
            if (LIBRAW_FOUND)
                resolve_version(package_version "${LIBRAW_VERSION}")
                message("    LIBRAW: " ${package_version} " [pkgconfig]")

                # LibRaw's .pc lists an explicit C++ runtime (-lstdc++). We always link
                # through the C++ compiler driver, which provides it implicitly, so drop
                # it to avoid a duplicate-library warning (it aliases libc++ on macOS).
                if (TARGET PkgConfig::LIBRAW)
                    get_target_property(_libraw_libs PkgConfig::LIBRAW INTERFACE_LINK_LIBRARIES)
                    if (_libraw_libs)
                        list(REMOVE_ITEM _libraw_libs "stdc++")
                        set_target_properties(PkgConfig::LIBRAW PROPERTIES INTERFACE_LINK_LIBRARIES "${_libraw_libs}")
                    endif ()
                endif ()

                target_link_libraries(mango-image ${INTERFACE} PkgConfig::LIBRAW)
            else ()
                message("    LIBRAW: no version [not found]")
            endif ()
        endif ()
    endif ()
endfunction()
